FROM mysql:5.7
LABEL maintainer="rodrigotmg@gmail.com"

# Copy the database schema to the init directory
ADD docker/mysql_ddl.sql /docker-entrypoint-initdb.d/mysql_ddl.sql

ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_USER=user1
ENV MYSQL_PASSWORD=password1
ENV MYSQL_DATABASE=test-db